schema_version: 1

context:
  name: databricks-sqlalchemy
  version: "2.0.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/databricks_sqlalchemy-${{ version }}.tar.gz
  sha256: 9e4edfcb1687b8c8fd420de0d83ba3a9cccf9cbbd16ca36d73a2aa42ba0abb88

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - databricks-sql-connector >=4.0.0
    - pyarrow >=14.0.1
    - sqlalchemy >=2.0.21

tests:
  - python:
      pip_check: false
      python_version: ${{ python_min }}.*
      imports:
        - databricks.sqlalchemy

about:
  homepage: https://github.com/databricks/databricks-sqlalchemy
  summary: Databricks SQLAlchemy plugin for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
