schema_version: 1

context:
  name: databricks-sqlalchemy
  version: "1.0.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/databricks_sqlalchemy-${{ version }}.tar.gz
  sha256: e0b33f5803393e4baf9c466cd38b75fa4b154e23d6a588ef172d534ce5e3914b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - databricks-sql-connector >=4.0.0
    - pyarrow >=14.0.1,<17
    - sqlalchemy >=1.3.24,<2.0.0

tests:
  - python:
      pip_check: false
      python_version: ${{ python_min }}.*
      imports:
        - databricks.sqlalchemy

about:
  homepage: https://github.com/databricks/databricks-sqlalchemy
  summary: Databricks SQLAlchemy plugin for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
