schema_version: 1

context:
  name: databricks-sqlalchemy
  version: 2.0.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/databricks_sqlalchemy-${{ version }}.tar.gz
  sha256: 3c457a4ca1c4a54782301f718340336de5f467b68b380b756dc655f007c4425d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - databricks-sql-connector >=4.0.0
    - pyarrow >=14.0.1,<17
    - sqlalchemy >=2.0.21

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports:
        - databricks.sqlalchemy

about:
  homepage: https://github.com/databricks/databricks-sqlalchemy
  summary: Databricks SQLAlchemy plugin for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
